export const jokes = [
  {
    hobby: "Sports & Fitness",
    age: "18-25",
    mood: "Happy",
    type: "Sarcastic",
    joke: "I told my trainer I wanted to do crunches, but now I only crunch chips.",
  },
  {
    hobby: "Sports & Fitness",
    age: "26-35",
    mood: "Relaxed",
    type: "Wholesome",
    joke: "Exercise is great, but so is napping after yoga.",
  },
  {
    hobby: "Sports & Fitness",
    age: "36-45",
    mood: "Energetic",
    type: "Pun-based",
    joke: "Why did the soccer player bring string to the game? To tie the score!",
  },
  {
    hobby: "Sports & Fitness",
    age: "46-60",
    mood: "Stressed",
    type: "Witty/Intellectual",
    joke: "They say exercise reduces stress. I’m stressed because I have to exercise!",
  },
  {
    hobby: "Sports & Fitness",
    age: "60+",
    mood: "Reflective",
    type: "Slapstick",
    joke: "I started walking to stay healthy. Then I tripped over the treadmill cord!",
  },
  {
    hobby: "Arts & Crafts",
    age: "18-25",
    mood: "Energetic",
    type: "Sarcastic",
    joke: "I tried knitting to relax... now I’m tangled in my own stress.",
  },
  {
    hobby: "Arts & Crafts",
    age: "26-35",
    mood: "Happy",
    type: "Wholesome",
    joke: "Every masterpiece starts with a single stroke of creativity!",
  },
  {
    hobby: "Arts & Crafts",
    age: "36-45",
    mood: "Relaxed",
    type: "Pun-based",
    joke: "Why was the artist always calm? They knew how to draw their feelings out.",
  },
  {
    hobby: "Arts & Crafts",
    age: "46-60",
    mood: "Stressed",
    type: "Witty/Intellectual",
    joke: "The only thing I create during craft time is a bigger mess.",
  },
  {
    hobby: "Arts & Crafts",
    age: "60+",
    mood: "Reflective",
    type: "Slapstick",
    joke: "I tried sculpting, but I ended up glued to the floor instead.",
  },
  {
    hobby: "Technology & Gaming",
    age: "18-25",
    mood: "Relaxed",
    type: "Sarcastic",
    joke: "Gaming is so relaxing... until you lose to a 12-year-old yelling in your ear.",
  },
  {
    hobby: "Technology & Gaming",
    age: "26-35",
    mood: "Happy",
    type: "Wholesome",
    joke: "Gaming brings people together—especially when you're all noobs in a team.",
  },
  {
    hobby: "Technology & Gaming",
    age: "36-45",
    mood: "Energetic",
    type: "Pun-based",
    joke: "Why don’t computers play hide and seek? They always get caught in the cache!",
  },
  {
    hobby: "Technology & Gaming",
    age: "46-60",
    mood: "Stressed",
    type: "Witty/Intellectual",
    joke: "Every tech issue has two solutions: reboot or blame the Wi-Fi.",
  },
  {
    hobby: "Technology & Gaming",
    age: "60+",
    mood: "Reflective",
    type: "Slapstick",
    joke: "I tried VR gaming but ended up walking into a wall. Realism at its best!",
  },
  {
    hobby: "Travel & Adventure",
    age: "18-25",
    mood: "Energetic",
    type: "Sarcastic",
    joke: "Backpacking is great—until you realize your bag is heavier than your ambition.",
  },
  {
    hobby: "Travel & Adventure",
    age: "26-35",
    mood: "Happy",
    type: "Wholesome",
    joke: "Every journey begins with a single step... and a suitcase full of snacks.",
  },
  {
    hobby: "Travel & Adventure",
    age: "36-45",
    mood: "Relaxed",
    type: "Pun-based",
    joke: "Why don’t mountains ever get tired? They’re always peaking!",
  },
  {
    hobby: "Travel & Adventure",
    age: "46-60",
    mood: "Stressed",
    type: "Witty/Intellectual",
    joke: "Travel stress: When your vacation feels like a full-time job.",
  },
  {
    hobby: "Travel & Adventure",
    age: "60+",
    mood: "Reflective",
    type: "Slapstick",
    joke: "I went zip-lining, and now I can’t zip my jacket. Adventure is rough!",
  },
  {
    hobby: "Cooking & Food",
    age: "18-25",
    mood: "Relaxed",
    type: "Sarcastic",
    joke: "Cooking is fun—until you realize you forgot half the ingredients.",
  },
  {
    hobby: "Cooking & Food",
    age: "26-35",
    mood: "Happy",
    type: "Wholesome",
    joke: "A home-cooked meal is love made edible!",
  },
  {
    hobby: "Cooking & Food",
    age: "36-45",
    mood: "Energetic",
    type: "Pun-based",
    joke: "Why did the chef break up with their partner? They just couldn’t make thyme!",
  },
  {
    hobby: "Cooking & Food",
    age: "46-60",
    mood: "Stressed",
    type: "Witty/Intellectual",
    joke: "I cook with wine. Sometimes it even goes into the food!",
  },
  {
    hobby: "Cooking & Food",
    age: "60+",
    mood: "Reflective",
    type: "Slapstick",
    joke: "I tried flipping a pancake but ended up flipping the whole pan instead.",
  },
];
